name: Help & Support
description: Get help with OpenCore-ISO setup or configuration
title: "[HELP] "
labels: ["question", "help-wanted"]

body:
body:
  - type: markdown
    attributes:
      value: |
        ## Need help with OpenCore-ISO?
        Before asking for help, please check:
        - The [README](https://github.com/LongQT-sea/OpenCore-ISO#readme) and its troubleshooting section
        - [Existing issues](https://github.com/LongQT-sea/OpenCore-ISO/issues) for similar problems
        - [Discussions](https://github.com/LongQT-sea/OpenCore-ISO/discussions) for community solutions
        **Have you starred this repo yet?** Show your support and help others find this project!

  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have read the [README.md](https://github.com/LongQT-sea/OpenCore-ISO?#about)
          required: true
        - label: I have searched existing issues and discussions
          required: true
        - label: I've starred the repo ⭐ (or will star it later!)
          required: false

  - type: dropdown
    attributes:
      label: macOS Version
      options:
        - macOS 26 Tahoe
        - macOS 15 Sequoia
        - macOS 14 Sonoma
        - macOS 13 Ventura
        - macOS 12 Monterey
        - macOS 11 Big Sur
        - macOS 10.15 Catalina
        - macOS 10.14 Mojave
        - Other/Legacy (specify below)
    validations:
      required: true

  - type: textarea
    attributes:
      label: System Info
      description: Host specs and VM configuration
      placeholder: |
        Proxmox/Host: 
        CPU: 
        RAM: 
        VM Config (key settings):
      render: shell
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem Description
      description: What's the issue?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What You've Tried
      description: Steps taken to resolve
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error Messages/Logs
      description: Include relevant errors or logs
      render: shell
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Screenshots or other details
    validations:
      required: false